[package]
name = "tailslint"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
tray-icon = "0.21.0"
muda = "0.17.0"
image = "0.25.6"
gtk = "0.18.2"
glib = "0.20.12"
